// <auto-generated />
using DnD_character_list;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DnD_character_list.Migrations
{
    [DbContext(typeof(DDInformationContext))]
    [Migration("20260506013957_AddClassTracking")]
    partial class AddClassTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DnD_character_list.Background", b =>
                {
                    b.Property<int>("IdBackground")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_background");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBackground"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Gm")
                        .HasColumnType("integer")
                        .HasColumnName("gm");

                    b.Property<string>("Invetary")
                        .HasColumnType("text")
                        .HasColumnName("invetary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Possesion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("possesion");

                    b.Property<string>("Source")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("source");

                    b.Property<string>("ToolOwnership")
                        .HasColumnType("text")
                        .HasColumnName("toolOwnership");

                    b.HasKey("IdBackground");

                    b.ToTable("Background", (string)null);
                });

            modelBuilder.Entity("DnD_character_list.Character", b =>
                {
                    b.Property<int>("IdCharacter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_character");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCharacter"));

                    b.Property<string>("Characteristiks")
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("characteristiks");

                    b.Property<int?>("CurHp")
                        .HasColumnType("integer")
                        .HasColumnName("cur_hp");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("Em")
                        .HasColumnType("integer")
                        .HasColumnName("em");

                    b.Property<int?>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int?>("Gm")
                        .HasColumnType("integer")
                        .HasColumnName("gm");

                    b.Property<int?>("Hitpoints")
                        .HasColumnType("integer")
                        .HasColumnName("hitpoints");

                    b.Property<int>("IdBackground")
                        .HasColumnType("integer")
                        .HasColumnName("ID_background");

                    b.Property<int>("IdSpecies")
                        .HasColumnType("integer")
                        .HasColumnName("ID_species");

                    b.Property<int?>("Kd")
                        .HasColumnType("integer")
                        .HasColumnName("kd");

                    b.Property<int?>("Mm")
                        .HasColumnType("integer")
                        .HasColumnName("mm");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PendingSkillChoices")
                        .HasColumnType("text")
                        .HasColumnName("pending_skill_choices");

                    b.Property<int?>("PendingSkillCount")
                        .HasColumnType("integer")
                        .HasColumnName("pending_skill_count");

                    b.Property<int?>("Pm")
                        .HasColumnType("integer")
                        .HasColumnName("pm");

                    b.Property<string>("PossesionNew")
                        .HasColumnType("text")
                        .HasColumnName("possesion_new");

                    b.Property<string>("Possession")
                        .HasColumnType("text")
                        .HasColumnName("possession");

                    b.Property<int?>("PrimaryClassId")
                        .HasColumnType("integer")
                        .HasColumnName("primary_class_id");

                    b.Property<bool>("SkillsPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("skills_pending");

                    b.Property<int?>("Sm")
                        .HasColumnType("integer")
                        .HasColumnName("sm");

                    b.Property<int?>("SpasLose")
                        .HasColumnType("integer")
                        .HasColumnName("spas_lose");

                    b.Property<int?>("SpasWin")
                        .HasColumnType("integer")
                        .HasColumnName("spas_win");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int?>("TimeHitpoints")
                        .HasColumnType("integer")
                        .HasColumnName("time_hitpoints");

                    b.Property<string>("Worldview")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("worldview");

                    b.HasKey("IdCharacter");

                    b.HasIndex("IdBackground");

                    b.HasIndex("IdSpecies");

                    b.ToTable("Character", (string)null);
                });

            modelBuilder.Entity("DnD_character_list.Class", b =>
                {
                    b.Property<int>("IdClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_class");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClass"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IdHitDice")
                        .HasColumnType("integer")
                        .HasColumnName("ID_hit_dice");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Possession")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("possession");

                    b.HasKey("IdClass");

                    b.HasIndex("IdHitDice");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("DnD_character_list.HitDice", b =>
                {
                    b.Property<int>("IdHitDice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_hit_dice");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHitDice"));

                    b.Property<string>("HitDice1")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("hit_dice");

                    b.HasKey("IdHitDice");

                    b.ToTable("Hit_dice", (string)null);
                });

            modelBuilder.Entity("DnD_character_list.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("IdItem");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("DnD_character_list.ItemInventory", b =>
                {
                    b.Property<int>("IdItem")
                        .HasColumnType("integer")
                        .HasColumnName("ID_item");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("integer")
                        .HasColumnName("ID_character");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("IdItem", "IdCharacter");

                    b.HasIndex("IdCharacter");

                    b.ToTable("Item_inventory", (string)null);
                });

            modelBuilder.Entity("DnD_character_list.Level", b =>
                {
                    b.Property<int>("Level1")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("IdClass")
                        .HasColumnType("integer")
                        .HasColumnName("ID_class");

                    b.Property<string>("Cells")
                        .HasColumnType("text")
                        .HasColumnName("cells");

                    b.Property<string>("ClassTableFeatures")
                        .HasColumnType("text")
                        .HasColumnName("class_table_features");

                    b.Property<string>("Skills")
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.HasKey("Level1", "IdClass");

                    b.HasIndex("IdClass");

                    b.ToTable("Level", (string)null);
                });

            modelBuilder.Entity("DnD_character_list.Species", b =>
                {
                    b.Property<int>("IdSpecies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_species");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpecies"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("source");

                    b.Property<string>("SpeciesChaTics")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("species_cha-tics");

                    b.Property<string>("SpeciesSkills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("species_skills");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("speed");

                    b.HasKey("IdSpecies");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("DnD_character_list.Spell", b =>
                {
                    b.Property<int>("IdSpell")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_spell");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSpell"));

                    b.Property<int>("CellLevel")
                        .HasColumnType("integer")
                        .HasColumnName("cell_level");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("components");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Duration")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("duration");

                    b.Property<string>("MaterialComponent")
                        .HasColumnType("text")
                        .HasColumnName("material_component");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<string>("Peculiarities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("peculiarities");

                    b.Property<string>("Range")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("range");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("school");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("source");

                    b.Property<string>("Time")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("time");

                    b.Property<string>("Upper")
                        .HasColumnType("text")
                        .HasColumnName("upper");

                    b.HasKey("IdSpell")
                        .HasName("PK_Spells_1");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("DnD_character_list.Trait", b =>
                {
                    b.Property<int>("IdTrait")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID_trait");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTrait"));

                    b.Property<string>("CharTics")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("char-tics");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("IdTrait");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("Multiclass", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("integer")
                        .HasColumnName("ID_character");

                    b.Property<int>("IdClass")
                        .HasColumnType("integer")
                        .HasColumnName("ID_class");

                    b.HasKey("Level", "IdCharacter", "IdClass");

                    b.HasIndex("IdCharacter");

                    b.HasIndex("Level", "IdClass");

                    b.ToTable("Multiclass", (string)null);
                });

            modelBuilder.Entity("SpellInventory", b =>
                {
                    b.Property<int>("IdSpell")
                        .HasColumnType("integer")
                        .HasColumnName("ID_spell");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("integer")
                        .HasColumnName("ID_character");

                    b.HasKey("IdSpell", "IdCharacter");

                    b.HasIndex("IdCharacter");

                    b.ToTable("Spell_inventory", (string)null);
                });

            modelBuilder.Entity("TraitInventory", b =>
                {
                    b.Property<int>("IdTrait")
                        .HasColumnType("integer")
                        .HasColumnName("ID_trait");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("integer")
                        .HasColumnName("ID_character");

                    b.HasKey("IdTrait", "IdCharacter");

                    b.HasIndex("IdCharacter");

                    b.ToTable("Trait_inventory", (string)null);
                });

            modelBuilder.Entity("DnD_character_list.Character", b =>
                {
                    b.HasOne("DnD_character_list.Background", "IdBackgroundNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdBackground")
                        .IsRequired()
                        .HasConstraintName("FK_Character_Background");

                    b.HasOne("DnD_character_list.Species", "IdSpeciesNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdSpecies")
                        .IsRequired()
                        .HasConstraintName("FK_Character_Species");

                    b.Navigation("IdBackgroundNavigation");

                    b.Navigation("IdSpeciesNavigation");
                });

            modelBuilder.Entity("DnD_character_list.Class", b =>
                {
                    b.HasOne("DnD_character_list.HitDice", "IdHitDiceNavigation")
                        .WithMany("Classes")
                        .HasForeignKey("IdHitDice")
                        .IsRequired()
                        .HasConstraintName("FK_Class_Hit_dice");

                    b.Navigation("IdHitDiceNavigation");
                });

            modelBuilder.Entity("DnD_character_list.ItemInventory", b =>
                {
                    b.HasOne("DnD_character_list.Character", "IdCharacterNavigation")
                        .WithMany("ItemInventories")
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_Item_inventory_Character");

                    b.HasOne("DnD_character_list.Item", "IdItemNavigation")
                        .WithMany("ItemInventories")
                        .HasForeignKey("IdItem")
                        .IsRequired()
                        .HasConstraintName("FK_Item_inventory_Items");

                    b.Navigation("IdCharacterNavigation");

                    b.Navigation("IdItemNavigation");
                });

            modelBuilder.Entity("DnD_character_list.Level", b =>
                {
                    b.HasOne("DnD_character_list.Class", "IdClassNavigation")
                        .WithMany("Levels")
                        .HasForeignKey("IdClass")
                        .IsRequired()
                        .HasConstraintName("FK_Level_Class");

                    b.Navigation("IdClassNavigation");
                });

            modelBuilder.Entity("Multiclass", b =>
                {
                    b.HasOne("DnD_character_list.Character", null)
                        .WithMany()
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_Multiclass_Character");

                    b.HasOne("DnD_character_list.Level", null)
                        .WithMany()
                        .HasForeignKey("Level", "IdClass")
                        .IsRequired()
                        .HasConstraintName("FK_Multiclass_Level");
                });

            modelBuilder.Entity("SpellInventory", b =>
                {
                    b.HasOne("DnD_character_list.Character", null)
                        .WithMany()
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_Spell_inventory_Character");

                    b.HasOne("DnD_character_list.Spell", null)
                        .WithMany()
                        .HasForeignKey("IdSpell")
                        .IsRequired()
                        .HasConstraintName("FK_Spell_inventory_Spells");
                });

            modelBuilder.Entity("TraitInventory", b =>
                {
                    b.HasOne("DnD_character_list.Character", null)
                        .WithMany()
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_Trait_inventory_Character");

                    b.HasOne("DnD_character_list.Trait", null)
                        .WithMany()
                        .HasForeignKey("IdTrait")
                        .IsRequired()
                        .HasConstraintName("FK_Trait_inventory_Traits");
                });

            modelBuilder.Entity("DnD_character_list.Background", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("DnD_character_list.Character", b =>
                {
                    b.Navigation("ItemInventories");
                });

            modelBuilder.Entity("DnD_character_list.Class", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("DnD_character_list.HitDice", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("DnD_character_list.Item", b =>
                {
                    b.Navigation("ItemInventories");
                });

            modelBuilder.Entity("DnD_character_list.Species", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
